# Generated by Django 4.2.1 on 2023-05-08 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OhMyDog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Clientes',
            new_name='Cliente',
        ),
    ]
