# Generated by Django 4.2.1 on 2023-05-08 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OhMyDog', '0002_rename_clientes_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoDelTurno',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FranjaHoraria',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDeAtencion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_del_turno', models.DateField()),
                ('fecha_de_solicitud', models.DateTimeField()),
                ('notas', models.TextField()),
                ('cliente_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OhMyDog.cliente')),
                ('estado_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OhMyDog.estadodelturno')),
                ('franja_horaria_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OhMyDog.franjahoraria')),
                ('tipo_atencion_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OhMyDog.tipodeatencion')),
            ],
        ),
    ]
