# Generated by Django 4.2.1 on 2023-05-08 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OhMyDog', '0003_estadodelturno_franjahoraria_tipodeatencion_turno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='notas',
            field=models.TextField(null=True),
        ),
    ]
