# Generated by Django 4.2.1 on 2023-05-09 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OhMyDog', '0004_alter_turno_notas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(max_length=30),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='estadodelturno',
            name='nombre',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='franjahoraria',
            name='nombre',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='tipodeatencion',
            name='nombre',
            field=models.CharField(max_length=30),
        ),
        migrations.CreateModel(
            name='Perro',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=35)),
                ('raza', models.CharField(max_length=255)),
                ('peso', models.IntegerField()),
                ('descripcion', models.CharField(max_length=255)),
                ('fecha_de_nacimiento', models.DateField()),
                ('sexo', models.CharField(choices=[('M', 'Macho'), ('H', 'Hembra')], max_length=1)),
                ('dueño', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OhMyDog.cliente')),
            ],
        ),
    ]
