# Generated by Django 4.2.1 on 2023-05-10 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OhMyDog', '0009_alter_usuario_cliente_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='mail',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
