# Generated by Django 4.2.1 on 2023-05-19 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OhMyDog', '0011_delete_tipodeusuario_alter_usuario_cliente_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perro',
            name='dueño',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='OhMyDog.cliente'),
        ),
    ]
