# Generated by Django 4.2.1 on 2023-05-19 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OhMyDog', '0013_alter_perro_dueño_alter_usuario_cliente_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='cliente_id',
        ),
        migrations.AddField(
            model_name='usuario',
            name='cliente',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='OhMyDog.cliente'),
        ),
    ]
