# Generated by Django 4.2.1 on 2023-05-26 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OhMyDog', '0018_alter_usuario_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='fecha_del_turno',
            field=models.DateField(null=True),
        ),
    ]
