# Generated by Django 4.2.1 on 2023-05-26 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OhMyDog', '0019_alter_turno_fecha_del_turno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='fecha_del_turno',
            field=models.DateField(),
        ),
    ]
