# Generated by Django 4.2.1 on 2023-05-26 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OhMyDog', '0020_alter_turno_fecha_del_turno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='turno',
            old_name='cliente_id',
            new_name='cliente',
        ),
        migrations.RenameField(
            model_name='turno',
            old_name='estado_id',
            new_name='estado',
        ),
        migrations.RenameField(
            model_name='turno',
            old_name='franja_horaria_id',
            new_name='franja_horaria',
        ),
        migrations.RenameField(
            model_name='turno',
            old_name='tipo_atencion_id',
            new_name='tipo_atencion',
        ),
    ]
