# Generated by Django 4.2.1 on 2023-06-01 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OhMyDog', '0024_alter_atencion_perro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Desparacitacion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('dosis', models.CharField(max_length=255)),
                ('farmaco', models.CharField(max_length=255)),
                ('parasito', models.CharField(max_length=255)),
                ('atencion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='OhMyDog.atencion')),
            ],
        ),
    ]
