# Generated by Django 4.2.1 on 2023-06-01 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OhMyDog', '0027_alter_perro_peso'),
    ]

    operations = [
        migrations.AddField(
            model_name='perro',
            name='tiene_castracion',
            field=models.BooleanField(default=False),
        ),
    ]
