# Generated by Django 4.2.1 on 2023-06-02 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OhMyDog', '0030_turno_perro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turno',
            name='perro',
        ),
    ]
