# Generated by Django 4.2.1 on 2023-06-02 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OhMyDog', '0031_remove_turno_perro'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='perro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='OhMyDog.perro'),
        ),
    ]
