# Generated by Django 4.2.1 on 2023-06-10 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OhMyDog', '0033_alter_perro_dueño'),
    ]

    operations = [
        migrations.RenameField(
            model_name='desparacitacion',
            old_name='parasito',
            new_name='diagnostico',
        ),
    ]
