# Generated by Django 4.2.1 on 2023-06-10 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OhMyDog', '0033_alter_perro_dueño'),
    ]

    operations = [
        migrations.CreateModel(
            name='etapaVidaPerro',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='tamanioPerro',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Adopcion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(null=True)),
                ('nombre', models.CharField(max_length=30)),
                ('sexo', models.CharField(choices=[('M', 'Macho'), ('H', 'Hembra')], max_length=1)),
                ('castrado', models.CharField(choices=[('S', 'Si'), ('N', 'No')], max_length=1)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OhMyDog.cliente')),
                ('etapa_vida_perro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OhMyDog.etapavidaperro')),
                ('tamanio_perro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OhMyDog.tamanioperro')),
            ],
        ),
    ]
