# Generated by Django 4.2.1 on 2023-06-11 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OhMyDog', '0034_etapavidaperro_tamanioperro_adopcion'),
        ('OhMyDog', '0034_rename_parasito_desparacitacion_diagnostico'),
    ]

    operations = [
    ]
