# Generated by Django 4.2.1 on 2023-06-12 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OhMyDog', '0036_vacunacion_fabricante_vacunacion_num_lote_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adopcion',
            name='adoptado',
            field=models.BooleanField(default=False),
        ),
    ]
