# Generated by Django 4.2.1 on 2023-06-12 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OhMyDog', '0037_adopcion_adoptado'),
        ('OhMyDog', '0038_desparacitacion_fabricante_desparacitacion_num_lote_and_more'),
    ]

    operations = [
    ]
