# Generated by Django 4.2.1 on 2023-06-17 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OhMyDog', '0041_paseador'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaseadorCuidador',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('latitud', models.TextField()),
                ('longitud', models.TextField()),
                ('franja_horaria', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('P', 'Paseador'), ('C', 'Cuidador')], max_length=1)),
            ],
        ),
        migrations.DeleteModel(
            name='Paseador',
        ),
    ]
