# Generated by Django 4.2.1 on 2023-06-26 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OhMyDog', '0043_remove_turno_notas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario_interesa_adopcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Adopcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OhMyDog.adopcion')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OhMyDog.cliente')),
            ],
        ),
    ]
