# Generated by Django 4.2.1 on 2023-06-26 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OhMyDog', '0044_usuario_interesa_adopcion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario_interesa_adopcion',
            old_name='Adopcion',
            new_name='adopcion',
        ),
    ]
