# Generated by Django 4.2.1 on 2023-06-26 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OhMyDog', '0046_alter_usuario_interesa_adopcion_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario_tiene_informacion_busqueda',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('busqueda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OhMyDog.busqueda')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OhMyDog.cliente')),
            ],
        ),
    ]
