# Generated by Django 4.2.1 on 2023-06-27 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OhMyDog', '0049_donacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='donacion',
            name='activa',
            field=models.BooleanField(default=True),
        ),
    ]
