# Generated by Django 4.2.1 on 2023-06-27 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OhMyDog', '0050_donacion_activa'),
    ]

    operations = [
        migrations.AddField(
            model_name='donacion',
            name='monto_objetivo',
            field=models.DecimalField(decimal_places=2, default=10000, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donacion',
            name='monto_recaudado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
