# Generated by Django 4.2.1 on 2023-06-27 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OhMyDog', '0051_donacion_monto_objetivo_donacion_monto_recaudado'),
    ]

    operations = [
        migrations.AddField(
            model_name='donacion',
            name='cantidad_donaciones',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
