# Generated by Django 4.2.1 on 2023-07-03 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OhMyDog', '0052_donacion_cantidad_donaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donacion',
            name='cantidad_donaciones',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='donacion',
            name='monto_recaudado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='Cruza',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('sexo', models.CharField(choices=[('M', 'Macho'), ('H', 'Hembra')], max_length=1)),
                ('raza', models.TextField()),
                ('edad_meses', models.IntegerField()),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('color', models.CharField(max_length=30)),
                ('antecedentes_salud', models.TextField(null=True)),
                ('foto', models.ImageField(upload_to='fotos/')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OhMyDog.cliente')),
                ('intereses', models.ManyToManyField(blank=True, to='OhMyDog.cruza')),
            ],
        ),
    ]
