# Generated by Django 4.2.1 on 2023-07-06 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OhMyDog', '0053_alter_donacion_cantidad_donaciones_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('transaccion_id', models.IntegerField(primary_key=True, serialize=False)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('campania', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OhMyDog.donacion')),
            ],
        ),
    ]
