# Generated by Django 4.2.1 on 2023-07-06 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OhMyDog', '0054_transaccion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaccion',
            name='transaccion_id',
        ),
        migrations.AddField(
            model_name='transaccion',
            name='finalizada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='id',
            field=models.BigAutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
