# Generated by Django 4.2.1 on 2023-07-09 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OhMyDog', '0057_descuento'),
    ]

    operations = [
        migrations.AddField(
            model_name='cruza',
            name='ultimo_celo',
            field=models.DateField(blank=True, null=True),
        ),
    ]
