# Generated by Django 4.2.1 on 2023-07-12 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OhMyDog', '0058_cruza_ultimo_celo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TipoDeDosisVacunacion',
        ),
        migrations.AlterModelOptions(
            name='adopcion',
            options={'verbose_name_plural': 'Adopciones'},
        ),
        migrations.AlterModelOptions(
            name='atencion',
            options={'verbose_name_plural': 'Atenciones'},
        ),
        migrations.AlterModelOptions(
            name='desparacitacion',
            options={'verbose_name_plural': 'Desparasitaciones'},
        ),
        migrations.AlterModelOptions(
            name='donacion',
            options={'verbose_name_plural': 'Donaciones'},
        ),
        migrations.AlterModelOptions(
            name='estadodelturno',
            options={'verbose_name_plural': '(LT) Estados_del_turno'},
        ),
        migrations.AlterModelOptions(
            name='etapavidaperro',
            options={'verbose_name_plural': '(LT) Etapas_de_vida'},
        ),
        migrations.AlterModelOptions(
            name='franjahoraria',
            options={'verbose_name_plural': '(LT) Franjas_horarias'},
        ),
        migrations.AlterModelOptions(
            name='paseadorcuidador',
            options={'verbose_name_plural': 'Paseadores_cuidadores'},
        ),
        migrations.AlterModelOptions(
            name='tamanioperro',
            options={'verbose_name_plural': '(LT) Tamaños_perro'},
        ),
        migrations.AlterModelOptions(
            name='tipodeatencion',
            options={'verbose_name_plural': '(LT) Tipos_atencion'},
        ),
        migrations.AlterModelOptions(
            name='vacunacion',
            options={'verbose_name_plural': 'Vacunaciones'},
        ),
        migrations.AlterField(
            model_name='adopcion',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adopciones', to='OhMyDog.cliente'),
        ),
        migrations.AlterField(
            model_name='busqueda',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='busquedas', to='OhMyDog.cliente'),
        ),
        migrations.AlterField(
            model_name='cruza',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cruzas', to='OhMyDog.cliente'),
        ),
    ]
