# Generated by Django 4.2.1 on 2023-07-12 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OhMyDog', '0059_delete_tipodedosisvacunacion_alter_adopcion_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaccion',
            options={'verbose_name_plural': 'Transacciones'},
        ),
        migrations.AlterModelOptions(
            name='usuariointeresaadopcion',
            options={'verbose_name_plural': 'Usuario_interesa_adopcion'},
        ),
        migrations.AlterModelOptions(
            name='usuariotieneinformacionbusqueda',
            options={'verbose_name_plural': 'Usuario_tiene_informacion'},
        ),
    ]
